name: Publish
on: [ push ]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI-SKIP]')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/wrapper-validation-action@v2
      - id: grant-permission-to-gradlew
        run: chmod +x ./gradlew
      - name: Generate build number
        if: ${{ !env.ACT }}
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1.0.2
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref_name }}
      - name: Publish
        run: ./gradlew -Dorg.gradle.s3.endpoint=${{ env.S3_ENDPOINT }} publish --stacktrace -Peula=true
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_URI: ${{ secrets.S3_URI }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
